// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/calculator.dart';
import 'api/converter_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'history.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1602414036;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_calculator_flutter_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  BmiResult crateApiConverterApiCalculateBmi({
    required double weightKg,
    required double heightM,
  });

  DiscountResult crateApiConverterApiCalculateDiscount({
    required double originalPrice,
    required double discountPercentage,
  });

  GstResult crateApiConverterApiCalculateGst({
    required double amount,
    required double gstPercentage,
    required bool addGst,
  });

  String? crateApiConverterApiConvertNumeral({
    required String value,
    required int fromBase,
    required int toBase,
  });

  double crateApiConverterApiConvertStandard({
    required double value,
    required FfiUnit fromUnit,
    required FfiUnit toUnit,
  });

  CalcResult crateApiCalculatorEvaluate({
    required String expression,
    required bool isDegree,
    required double ansValue,
  });

  String crateApiCalculatorFormatResult({
    required double value,
    required int maxPrecision,
  });

  List<FfiConverterCategory> crateApiConverterApiGetConverterCategories();

  void crateApiCalculatorHistoryAdd({
    required String expression,
    required String result,
  });

  void crateApiCalculatorHistoryClear();

  void crateApiCalculatorHistoryDelete({required BigInt index});

  List<HistoryEntry> crateApiCalculatorHistoryGetAll();

  Future<void> crateApiCalculatorHistoryLoad({required String path});

  Future<void> crateApiCalculatorHistorySave({required String path});

  void crateApiCalculatorMemoryAdd({required double value});

  void crateApiCalculatorMemoryClear();

  double? crateApiCalculatorMemoryRecall();

  void crateApiCalculatorMemoryStore({required double value});

  void crateApiCalculatorMemorySubtract({required double value});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  BmiResult crateApiConverterApiCalculateBmi({
    required double weightKg,
    required double heightM,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(weightKg, serializer);
          sse_encode_f_64(heightM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bmi_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiCalculateBmiConstMeta,
        argValues: [weightKg, heightM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiCalculateBmiConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_bmi",
        argNames: ["weightKg", "heightM"],
      );

  @override
  DiscountResult crateApiConverterApiCalculateDiscount({
    required double originalPrice,
    required double discountPercentage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(originalPrice, serializer);
          sse_encode_f_64(discountPercentage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_discount_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiCalculateDiscountConstMeta,
        argValues: [originalPrice, discountPercentage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiCalculateDiscountConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_discount",
        argNames: ["originalPrice", "discountPercentage"],
      );

  @override
  GstResult crateApiConverterApiCalculateGst({
    required double amount,
    required double gstPercentage,
    required bool addGst,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(amount, serializer);
          sse_encode_f_64(gstPercentage, serializer);
          sse_encode_bool(addGst, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_gst_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiCalculateGstConstMeta,
        argValues: [amount, gstPercentage, addGst],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiCalculateGstConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_gst",
        argNames: ["amount", "gstPercentage", "addGst"],
      );

  @override
  String? crateApiConverterApiConvertNumeral({
    required String value,
    required int fromBase,
    required int toBase,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(value, serializer);
          sse_encode_u_32(fromBase, serializer);
          sse_encode_u_32(toBase, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiConvertNumeralConstMeta,
        argValues: [value, fromBase, toBase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiConvertNumeralConstMeta =>
      const TaskConstMeta(
        debugName: "convert_numeral",
        argNames: ["value", "fromBase", "toBase"],
      );

  @override
  double crateApiConverterApiConvertStandard({
    required double value,
    required FfiUnit fromUnit,
    required FfiUnit toUnit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          sse_encode_box_autoadd_ffi_unit(fromUnit, serializer);
          sse_encode_box_autoadd_ffi_unit(toUnit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiConvertStandardConstMeta,
        argValues: [value, fromUnit, toUnit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiConvertStandardConstMeta =>
      const TaskConstMeta(
        debugName: "convert_standard",
        argNames: ["value", "fromUnit", "toUnit"],
      );

  @override
  CalcResult crateApiCalculatorEvaluate({
    required String expression,
    required bool isDegree,
    required double ansValue,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(expression, serializer);
          sse_encode_bool(isDegree, serializer);
          sse_encode_f_64(ansValue, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_calc_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculatorEvaluateConstMeta,
        argValues: [expression, isDegree, ansValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorEvaluateConstMeta => const TaskConstMeta(
    debugName: "evaluate",
    argNames: ["expression", "isDegree", "ansValue"],
  );

  @override
  String crateApiCalculatorFormatResult({
    required double value,
    required int maxPrecision,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          sse_encode_u_32(maxPrecision, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorFormatResultConstMeta,
        argValues: [value, maxPrecision],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorFormatResultConstMeta =>
      const TaskConstMeta(
        debugName: "format_result",
        argNames: ["value", "maxPrecision"],
      );

  @override
  List<FfiConverterCategory> crateApiConverterApiGetConverterCategories() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ffi_converter_category,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConverterApiGetConverterCategoriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConverterApiGetConverterCategoriesConstMeta =>
      const TaskConstMeta(debugName: "get_converter_categories", argNames: []);

  @override
  void crateApiCalculatorHistoryAdd({
    required String expression,
    required String result,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(expression, serializer);
          sse_encode_String(result, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorHistoryAddConstMeta,
        argValues: [expression, result],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistoryAddConstMeta =>
      const TaskConstMeta(
        debugName: "history_add",
        argNames: ["expression", "result"],
      );

  @override
  void crateApiCalculatorHistoryClear() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorHistoryClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistoryClearConstMeta =>
      const TaskConstMeta(debugName: "history_clear", argNames: []);

  @override
  void crateApiCalculatorHistoryDelete({required BigInt index}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorHistoryDeleteConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistoryDeleteConstMeta =>
      const TaskConstMeta(debugName: "history_delete", argNames: ["index"]);

  @override
  List<HistoryEntry> crateApiCalculatorHistoryGetAll() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorHistoryGetAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistoryGetAllConstMeta =>
      const TaskConstMeta(debugName: "history_get_all", argNames: []);

  @override
  Future<void> crateApiCalculatorHistoryLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculatorHistoryLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistoryLoadConstMeta =>
      const TaskConstMeta(debugName: "history_load", argNames: ["path"]);

  @override
  Future<void> crateApiCalculatorHistorySave({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculatorHistorySaveConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorHistorySaveConstMeta =>
      const TaskConstMeta(debugName: "history_save", argNames: ["path"]);

  @override
  void crateApiCalculatorMemoryAdd({required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorMemoryAddConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorMemoryAddConstMeta =>
      const TaskConstMeta(debugName: "memory_add", argNames: ["value"]);

  @override
  void crateApiCalculatorMemoryClear() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorMemoryClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorMemoryClearConstMeta =>
      const TaskConstMeta(debugName: "memory_clear", argNames: []);

  @override
  double? crateApiCalculatorMemoryRecall() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorMemoryRecallConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorMemoryRecallConstMeta =>
      const TaskConstMeta(debugName: "memory_recall", argNames: []);

  @override
  void crateApiCalculatorMemoryStore({required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorMemoryStoreConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorMemoryStoreConstMeta =>
      const TaskConstMeta(debugName: "memory_store", argNames: ["value"]);

  @override
  void crateApiCalculatorMemorySubtract({required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalculatorMemorySubtractConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculatorMemorySubtractConstMeta =>
      const TaskConstMeta(debugName: "memory_subtract", argNames: ["value"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BmiResult dco_decode_bmi_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BmiResult(
      bmi: dco_decode_f_64(arr[0]),
      category: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiUnit dco_decode_box_autoadd_ffi_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_unit(raw);
  }

  @protected
  CalcResult dco_decode_calc_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CalcResult(
      value: dco_decode_f_64(arr[0]),
      formatted: dco_decode_String(arr[1]),
      exactFraction: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  DiscountResult dco_decode_discount_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiscountResult(
      amountSaved: dco_decode_f_64(arr[0]),
      finalPrice: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfiConverterCategory dco_decode_ffi_converter_category(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiConverterCategory(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      iconName: dco_decode_String(arr[2]),
      units: dco_decode_list_ffi_unit(arr[3]),
    );
  }

  @protected
  FfiUnit dco_decode_ffi_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiUnit(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      symbol: dco_decode_String(arr[2]),
      multiplier: dco_decode_f_64(arr[3]),
      offset: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  GstResult dco_decode_gst_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GstResult(
      gstAmount: dco_decode_f_64(arr[0]),
      totalAmount: dco_decode_f_64(arr[1]),
      originalAmount: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  HistoryEntry dco_decode_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HistoryEntry(
      expression: dco_decode_String(arr[0]),
      result: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<FfiConverterCategory> dco_decode_list_ffi_converter_category(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_ffi_converter_category)
        .toList();
  }

  @protected
  List<FfiUnit> dco_decode_list_ffi_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_unit).toList();
  }

  @protected
  List<HistoryEntry> dco_decode_list_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BmiResult sse_decode_bmi_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bmi = sse_decode_f_64(deserializer);
    var var_category = sse_decode_String(deserializer);
    return BmiResult(bmi: var_bmi, category: var_category);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FfiUnit sse_decode_box_autoadd_ffi_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_unit(deserializer));
  }

  @protected
  CalcResult sse_decode_calc_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_f_64(deserializer);
    var var_formatted = sse_decode_String(deserializer);
    var var_exactFraction = sse_decode_opt_String(deserializer);
    return CalcResult(
      value: var_value,
      formatted: var_formatted,
      exactFraction: var_exactFraction,
    );
  }

  @protected
  DiscountResult sse_decode_discount_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_amountSaved = sse_decode_f_64(deserializer);
    var var_finalPrice = sse_decode_f_64(deserializer);
    return DiscountResult(
      amountSaved: var_amountSaved,
      finalPrice: var_finalPrice,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfiConverterCategory sse_decode_ffi_converter_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_iconName = sse_decode_String(deserializer);
    var var_units = sse_decode_list_ffi_unit(deserializer);
    return FfiConverterCategory(
      id: var_id,
      name: var_name,
      iconName: var_iconName,
      units: var_units,
    );
  }

  @protected
  FfiUnit sse_decode_ffi_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_symbol = sse_decode_String(deserializer);
    var var_multiplier = sse_decode_f_64(deserializer);
    var var_offset = sse_decode_f_64(deserializer);
    return FfiUnit(
      id: var_id,
      name: var_name,
      symbol: var_symbol,
      multiplier: var_multiplier,
      offset: var_offset,
    );
  }

  @protected
  GstResult sse_decode_gst_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gstAmount = sse_decode_f_64(deserializer);
    var var_totalAmount = sse_decode_f_64(deserializer);
    var var_originalAmount = sse_decode_f_64(deserializer);
    return GstResult(
      gstAmount: var_gstAmount,
      totalAmount: var_totalAmount,
      originalAmount: var_originalAmount,
    );
  }

  @protected
  HistoryEntry sse_decode_history_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_expression = sse_decode_String(deserializer);
    var var_result = sse_decode_String(deserializer);
    return HistoryEntry(expression: var_expression, result: var_result);
  }

  @protected
  List<FfiConverterCategory> sse_decode_list_ffi_converter_category(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiConverterCategory>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_converter_category(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiUnit> sse_decode_list_ffi_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiUnit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_unit(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryEntry> sse_decode_list_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bmi_result(BmiResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.bmi, serializer);
    sse_encode_String(self.category, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_unit(FfiUnit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_unit(self, serializer);
  }

  @protected
  void sse_encode_calc_result(CalcResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.value, serializer);
    sse_encode_String(self.formatted, serializer);
    sse_encode_opt_String(self.exactFraction, serializer);
  }

  @protected
  void sse_encode_discount_result(
    DiscountResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.amountSaved, serializer);
    sse_encode_f_64(self.finalPrice, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffi_converter_category(
    FfiConverterCategory self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.iconName, serializer);
    sse_encode_list_ffi_unit(self.units, serializer);
  }

  @protected
  void sse_encode_ffi_unit(FfiUnit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.symbol, serializer);
    sse_encode_f_64(self.multiplier, serializer);
    sse_encode_f_64(self.offset, serializer);
  }

  @protected
  void sse_encode_gst_result(GstResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.gstAmount, serializer);
    sse_encode_f_64(self.totalAmount, serializer);
    sse_encode_f_64(self.originalAmount, serializer);
  }

  @protected
  void sse_encode_history_entry(HistoryEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.expression, serializer);
    sse_encode_String(self.result, serializer);
  }

  @protected
  void sse_encode_list_ffi_converter_category(
    List<FfiConverterCategory> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_converter_category(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_unit(List<FfiUnit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_unit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_entry(
    List<HistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
