// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../history.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

CalcResult evaluate({
  required String expression,
  required bool isDegree,
  required double ansValue,
}) => RustLib.instance.api.crateApiCalculatorEvaluate(
  expression: expression,
  isDegree: isDegree,
  ansValue: ansValue,
);

String formatResult({required double value, required int maxPrecision}) =>
    RustLib.instance.api.crateApiCalculatorFormatResult(
      value: value,
      maxPrecision: maxPrecision,
    );

void memoryStore({required double value}) =>
    RustLib.instance.api.crateApiCalculatorMemoryStore(value: value);

double? memoryRecall() => RustLib.instance.api.crateApiCalculatorMemoryRecall();

void memoryAdd({required double value}) =>
    RustLib.instance.api.crateApiCalculatorMemoryAdd(value: value);

void memorySubtract({required double value}) =>
    RustLib.instance.api.crateApiCalculatorMemorySubtract(value: value);

void memoryClear() => RustLib.instance.api.crateApiCalculatorMemoryClear();

void historyAdd({required String expression, required String result}) => RustLib
    .instance
    .api
    .crateApiCalculatorHistoryAdd(expression: expression, result: result);

List<HistoryEntry> historyGetAll() =>
    RustLib.instance.api.crateApiCalculatorHistoryGetAll();

void historyClear() => RustLib.instance.api.crateApiCalculatorHistoryClear();

void historyDelete({required BigInt index}) =>
    RustLib.instance.api.crateApiCalculatorHistoryDelete(index: index);

Future<void> historySave({required String path}) =>
    RustLib.instance.api.crateApiCalculatorHistorySave(path: path);

Future<void> historyLoad({required String path}) =>
    RustLib.instance.api.crateApiCalculatorHistoryLoad(path: path);

class CalcResult {
  final double value;
  final String formatted;
  final String? exactFraction;

  const CalcResult({
    required this.value,
    required this.formatted,
    this.exactFraction,
  });

  @override
  int get hashCode =>
      value.hashCode ^ formatted.hashCode ^ exactFraction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalcResult &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          formatted == other.formatted &&
          exactFraction == other.exactFraction;
}
