use std::collections::HashMap;
use crate::modular_math::error::ModError;
use crate::modular_math::mod_arith::{mod_reduce, mod_pow, is_prime};
use crate::modular_math::number_theory::{gcd, extended_gcd};

/// Returns the prime factorization of n as a list of (prime, exponent).
pub fn prime_factorization(mut n: i128) -> Vec<(i128, u32)> {
    n = n.abs();
    let mut factors = Vec::new();
    if n <= 1 {
        return factors;
    }
    
    let mut count = 0;
    while n % 2 == 0 {
        count += 1;
        n /= 2;
    }
    if count > 0 {
        factors.push((2, count));
    }
    
    let mut i = 3;
    while i * i <= n {
        let mut count = 0;
        while n % i == 0 {
            count += 1;
            n /= i;
        }
        if count > 0 {
            factors.push((i, count));
        }
        i += 2;
    }
    if n > 1 {
        factors.push((n, 1));
    }
    
    factors
}

/// Computes Euler's totient function φ(n).
pub fn euler_totient(n: i128) -> i128 {
    let n = n.abs();
    if n == 0 {
        return 0;
    }
    let mut result = n;
    let factors = prime_factorization(n);
    for (p, _) in factors {
        result -= result / p;
    }
    result
}

/// Computes the order of element a modulo n. Returns Err if gcd(a,n) > 1.
pub fn element_order(a: i128, n: i128) -> Result<i128, ModError> {
    if n <= 1 {
        return Err(ModError::InvalidModulus("Modulus must be > 1".to_string()));
    }
    let a_reduced = mod_reduce(a, n);
    if gcd(a_reduced, n) != 1 {
        return Err(ModError::InvalidExpression(format!("Order undefined: gcd({}, {}) != 1", a_reduced, n)));
    }
    
    let phi = euler_totient(n);
    let mut order = phi;
    let factors = prime_factorization(phi);
    
    // For each prime factor p of phi, if a^(phi/p) == 1, then the order divides phi/p.
    for (p, _) in factors {
        let mut temp = order;
        while temp % p == 0 && mod_pow(a_reduced, temp / p, n)? == 1 {
            temp /= p;
        }
        order = temp;
    }
    
    Ok(order)
}

/// Checks if a is a primitive root modulo n.
pub fn is_primitive_root(a: i128, n: i128) -> Result<bool, ModError> {
    if gcd(a, n) != 1 {
        return Ok(false);
    }
    let order = element_order(a, n)?;
    let phi = euler_totient(n);
    Ok(order == phi)
}

/// Helper to check if n has primitive roots. They exist iff n is 1, 2, 4, p^k, or 2*p^k for odd prime p.
pub fn has_primitive_roots(n: i128) -> bool {
    let n = n.abs();
    if n == 1 || n == 2 || n == 4 {
        return true;
    }
    let mut m = n;
    if m % 2 == 0 {
        m /= 2;
        if m % 2 == 0 {
            return false; // divisible by 4, and n > 4
        }
    }
    // Now m must be p^k for some odd prime p
    let factors = prime_factorization(m);
    factors.len() == 1
}

/// Returns all primitive roots modulo n.
pub fn primitive_roots(n: i128) -> Result<Vec<i128>, ModError> {
    if n <= 1 {
        return Err(ModError::InvalidModulus("Modulus must be > 1".to_string()));
    }
    if !has_primitive_roots(n) {
        return Err(ModError::NoPrimitiveRoot(format!("Z_{}* is not cyclic (no primitive roots exist)", n)));
    }
    
    let mut roots = Vec::new();
    let phi = euler_totient(n);
    let phi_phi = euler_totient(phi);
    
    // Find the first primitive root
    let mut g = -1;
    for i in 2..n {
        if gcd(i, n) == 1 {
            if is_primitive_root(i, n)? {
                g = i;
                break;
            }
        }
    }
    
    if g == -1 {
        return Err(ModError::NoPrimitiveRoot(format!("Could not find primitive root for {}", n)));
    }
    
    // The other primitive roots are g^k mod n where gcd(k, phi) == 1
    for k in 1..phi {
        if gcd(k, phi) == 1 {
            roots.push(mod_pow(g, k, n)?);
        }
    }
    
    roots.sort_unstable();
    Ok(roots)
}

/// Returns the cyclic subgroup generated by a modulo n.
pub fn cyclic_subgroup(a: i128, n: i128) -> Result<Vec<i128>, ModError> {
    if n <= 1 {
        return Err(ModError::InvalidModulus("Modulus must be > 1".to_string()));
    }
    let a_red = mod_reduce(a, n);
    let mut subgroup = Vec::new();
    let mut current = 1;
    
    // Keep multiplying by a until we hit a cycle or 0
    let mut seen = std::collections::HashSet::new();
    
    loop {
        if seen.contains(&current) {
            break;
        }
        seen.insert(current);
        subgroup.push(current);
        current = mod_reduce(current * a_red, n);
    }
    
    subgroup.sort_unstable();
    Ok(subgroup)
}

/// Returns the unit group Z_n* (elements coprime to n).
pub fn unit_group(n: i128) -> Vec<i128> {
    let mut units = Vec::new();
    let n = n.abs();
    if n <= 1 {
        return units;
    }
    for i in 1..n {
        if gcd(i, n) == 1 {
            units.push(i);
        }
    }
    units
}

/// Returns the additive inverse of a modulo n.
pub fn additive_inverse(a: i128, n: i128) -> i128 {
    let a_red = mod_reduce(a, n);
    if a_red == 0 {
        0
    } else {
        n - a_red
    }
}

/// Solves ax ≡ b (mod n). Returns all distinct solutions mod n.
pub fn solve_linear_congruence(a: i128, b: i128, n: i128) -> Result<Vec<i128>, ModError> {
    if n <= 0 {
        return Err(ModError::InvalidModulus("Modulus must be positive".to_string()));
    }
    let a_red = mod_reduce(a, n);
    let b_red = mod_reduce(b, n);
    
    let (g, x, _) = extended_gcd(a_red, n);
    if b_red % g != 0 {
        return Err(ModError::NoSolution(format!("No solution: {} does not divide {}", g, b_red)));
    }
    
    let mut solutions = Vec::new();
    let x0 = mod_reduce(x * (b_red / g), n);
    
    let step = n / g;
    for i in 0..g {
        solutions.push(mod_reduce(x0 + i * step, n));
    }
    
    solutions.sort_unstable();
    Ok(solutions)
}

/// Computes the discrete logarithm x such that base^x ≡ target (mod p).
/// Uses the Baby-step Giant-step algorithm.
/// Caps at p <= 1_000_000_000 for performance limits.
pub fn discrete_log(base: i128, target: i128, p: i128) -> Result<i128, ModError> {
    if p <= 1 {
        return Err(ModError::InvalidModulus("Modulus must be > 1".to_string()));
    }
    if p > 1_000_000_000 {
        return Err(ModError::TooLarge(format!("Modulus {} is too large for discrete log. Limit is 10^9.", p)));
    }
    let a = mod_reduce(base, p);
    let b = mod_reduce(target, p);
    
    // Special cases
    if b == 1 { return Ok(0); }
    if a == 0 {
        return if b == 0 { Ok(1) } else { Err(ModError::NoSolution(format!("No solution for 0^x = {} mod {}", b, p))) };
    }
    
    // Baby-step Giant-step
    let m = (p as f64).sqrt().ceil() as i128;
    
    let mut table = HashMap::new();
    let mut current = 1;
    for j in 0..m {
        // Store the earliest j
        table.entry(current).or_insert(j);
        current = mod_reduce(current * a, p);
    }
    
    let factor = mod_pow(crate::modular_math::mod_arith::mod_inv(a, p)?, m, p)?;
    
    current = b;
    for i in 0..m {
        if let Some(&j) = table.get(&current) {
            return Ok(i * m + j);
        }
        current = mod_reduce(current * factor, p);
    }
    
    Err(ModError::NoSolution(format!("No discrete log found for {}^x = {} mod {}", a, b, p)))
}
